version: 1
formatters:
  default:
    format: '%(asctime)s | %(levelname)-8s | %(name)-30s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [ default ]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [ default ]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [ default ]
    level: INFO
    propagate: false
  app:
    handlers: [ default ]
    level: DEBUG
    propagate: false
root:
  level: INFO
  handlers: [ default ]
